// <auto-generated />
namespace PassionProject_YejunSon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserRestaurantsFolder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRestaurantsFolder));
        
        string IMigrationMetadata.Id
        {
            get { return "202402092132020_User-RestaurantsFolder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
