// <auto-generated />
namespace PassionProject_YejunSon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Editusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Editusers));
        
        string IMigrationMetadata.Id
        {
            get { return "202402130455068_Edit-users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
